/**
 * Faculty Subject Preferences Modal Component
 * Modal for managing faculty subject preferences with manual and auto-generation capabilities
 * Uses subject_tag (text) instead of subject_id for historical preservation
 */

import React, { useEffect, useRef, useState } from 'react';
import {
  fetchAllFacultySubjectPreferences,
  fetchFacultySubjectPreferences,
  fetchAvailableSubjectsForFaculty,
  addFacultySubjectPreference,
  deleteFacultySubjectPreference,
  fetchFacultyPreferenceRecords,
  deleteFacultyPreferenceRecord,
  autoGenerateFacultySubjectPreferences,
  autoGenerateSpecializationFromPreferences,
} from '../services/facultySubjectPreferencesApi.js';
import './FacultySubjectPreferencesModal.css';

const PRIORITY_LABELS = {
  1: 'High',
  2: 'Capable',
  3: 'Fallback',
};

const PRIORITY_COLORS = {
  1: '#d32f2f', // Red for High
  2: '#f57c00', // Amber for Capable
  3: '#1976d2', // Blue for Fallback
};

export default function FacultySubjectPreferencesModal({ facultyId, facultyName, onClose, onSaved }) {
  const [preferences, setPreferences] = useState([]);
  const [availableSubjects, setAvailableSubjects] = useState([]);
  const [tagUsageCounts, setTagUsageCounts] = useState({});
  const [isSubjectMenuOpen, setIsSubjectMenuOpen] = useState(false);
  const [subjectSearchQuery, setSubjectSearchQuery] = useState('');
  const [prepLimit, setPrepLimit] = useState(4);
  const [facultyMaxUnits, setFacultyMaxUnits] = useState(0);
  const [usedTaggedUnits, setUsedTaggedUnits] = useState(0);
  const [remainingUnits, setRemainingUnits] = useState(0);
  const [selectedSubjectCode, setSelectedSubjectCode] = useState('');
  const [selectedPriority, setSelectedPriority] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [autoGeneratedPreview, setAutoGeneratedPreview] = useState([]);
  const [isAdding, setIsAdding] = useState(false);
  const [preferenceRecords, setPreferenceRecords] = useState([]);
  const [preferenceRecordsPageSize, setPreferenceRecordsPageSize] = useState(20);
  const [preferenceRecordsTotal, setPreferenceRecordsTotal] = useState(0);
  const [preferenceRecordsHasMore, setPreferenceRecordsHasMore] = useState(false);
  const [recordLoadingMore, setRecordLoadingMore] = useState(false);
  const [recordLoading, setRecordLoading] = useState(true);
  const [recordError, setRecordError] = useState(null);
  const [recordActionId, setRecordActionId] = useState(null);
  const [confirmDialog, setConfirmDialog] = useState(null);
  const subjectMenuRef = useRef(null);
  const subjectSearchInputRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (subjectMenuRef.current && !subjectMenuRef.current.contains(event.target)) {
        setIsSubjectMenuOpen(false);
        setSubjectSearchQuery('');
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    if (isSubjectMenuOpen) {
      window.requestAnimationFrame(() => {
        subjectSearchInputRef.current?.focus();
      });
    }
  }, [isSubjectMenuOpen]);

  // Fetch initial data
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        setError(null);

        const [preferencesData, subjectsData, allPreferences] = await Promise.all([
          fetchFacultySubjectPreferences(facultyId),
          fetchAvailableSubjectsForFaculty(facultyId),
          fetchAllFacultySubjectPreferences().catch(() => ({})),
        ]);

        const recordsData = await fetchFacultyPreferenceRecords(facultyId, { limit: 20, offset: 0 }).catch((err) => {
          setRecordError(err instanceof Error ? err.message : 'Failed to load preference records');
          return { records: [], limit: 20, offset: 0, count: 0, hasMore: false };
        });

        const usageCounts = {};
        for (const prefs of Object.values(allPreferences || {})) {
          for (const pref of prefs || []) {
            const code = String(pref.subject_tag || '').trim().toUpperCase();
            if (!code) continue;
            usageCounts[code] = (usageCounts[code] || 0) + 1;
          }
        }

        // modal data loaded

        setPreferences(preferencesData.preferences || []);
        setPrepLimit(Number(preferencesData.prepLimit ?? 4));
        setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
        setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
        setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));
        setTagUsageCounts(usageCounts);
        setAvailableSubjects(subjectsData.subjects || []);
        setPreferenceRecords(recordsData.records || []);
        setPreferenceRecordsPageSize(Number(recordsData.limit || 20));
        setPreferenceRecordsTotal(Number(recordsData.count || recordsData.records?.length || 0));
        setPreferenceRecordsHasMore(Boolean(recordsData.hasMore));
      } catch (err) {
        console.error('❌ Error loading data:', err);
        setError(err instanceof Error ? err.message : 'Failed to load data');
      } finally {
        setLoading(false);
        setRecordLoading(false);
      }
    };

    loadData();
  }, [facultyId]);

  const refreshPreferenceRecords = async () => {
    try {
      setRecordLoading(true);
      setRecordError(null);
      const recordsData = await fetchFacultyPreferenceRecords(facultyId, { limit: preferenceRecordsPageSize, offset: 0 });
      setPreferenceRecords(recordsData.records || []);
      setPreferenceRecordsPageSize(Number(recordsData.limit || preferenceRecordsPageSize));
      setPreferenceRecordsTotal(Number(recordsData.count || recordsData.records?.length || 0));
      setPreferenceRecordsHasMore(Boolean(recordsData.hasMore));
    } catch (err) {
      setRecordError(err instanceof Error ? err.message : 'Failed to load preference records');
      setPreferenceRecords([]);
      setPreferenceRecordsHasMore(false);
    } finally {
      setRecordLoading(false);
    }
  };

  const handleLoadMorePreferenceRecords = async () => {
    try {
      setRecordError(null);
      setRecordLoadingMore(true);
      const recordsData = await fetchFacultyPreferenceRecords(facultyId, {
        limit: preferenceRecordsPageSize,
        offset: preferenceRecords.length,
      });

      setPreferenceRecords((current) => [...current, ...(recordsData.records || [])]);
      setPreferenceRecordsPageSize(Number(recordsData.limit || preferenceRecordsPageSize));
      setPreferenceRecordsTotal(Number(recordsData.count || preferenceRecordsTotal));
      setPreferenceRecordsHasMore(Boolean(recordsData.hasMore));
    } catch (err) {
      setRecordError(err instanceof Error ? err.message : 'Failed to load more preference records');
    } finally {
      setRecordLoadingMore(false);
    }
  };

  // Handle adding a new preference
  const handleAddPreference = async () => {
    if (!selectedSubjectCode) {
      setError('Please select a subject');
      return;
    }

    // Client-side remaining units check
    const sel = availableSubjects.find((s) => s.subject_code === selectedSubjectCode);
    const selUnits = Number(sel?.subject_units || 0);
    if (remainingUnits <= 0 || selUnits > remainingUnits) {
      setError(`Cannot add subject: only ${remainingUnits} unit(s) remaining for this faculty.`);
      return;
    }

    try {
      setError(null);
      setIsAdding(true);

      await addFacultySubjectPreference(facultyId, {
        subjectTag: selectedSubjectCode.toUpperCase(),
        priorityLevel: Number(selectedPriority),
      });

      // Refresh preferences
      const preferencesData = await fetchFacultySubjectPreferences(facultyId);
      setPreferences(preferencesData.preferences || []);
      setPrepLimit(Number(preferencesData.prepLimit ?? 4));
      setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
      setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
      setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));

      // Reset form
      setSelectedSubjectCode('');
      setSelectedPriority('');
      setSubjectSearchQuery('');
      setIsSubjectMenuOpen(false);
      setSuccessMessage('Subject preference added successfully');

      await refreshPreferenceRecords();

      // Clear success message after 3 seconds
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error adding preference:', err);
      setError(err instanceof Error ? err.message : 'Failed to add preference');
    } finally {
      setIsAdding(false);
    }
  };

  const executeDeletePreference = async (subjectTag) => {
    try {
      setError(null);

      await deleteFacultySubjectPreference(facultyId, subjectTag);

      // Refresh preferences
      const preferencesData = await fetchFacultySubjectPreferences(facultyId);
      setPreferences(preferencesData.preferences || []);
      setPrepLimit(Number(preferencesData.prepLimit ?? 4));
      setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
      setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
      setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));
      setSubjectSearchQuery('');
      await refreshPreferenceRecords();

      setSuccessMessage('Subject preference deleted successfully');
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error deleting preference:', err);
      setError(err instanceof Error ? err.message : 'Failed to delete preference');
    }
  };

  // Handle deleting a preference
  const handleDeletePreference = async (subjectTag) => {
    setConfirmDialog({
      type: 'delete-preference',
      title: 'Delete preference?',
      message: 'Are you sure you want to delete this preference?',
      confirmLabel: 'Delete preference',
      subjectTag,
    });
  };

  // Handle updating priority
  const handleUpdatePriority = async (subjectTag, newPriority) => {
    try {
      setError(null);

      await addFacultySubjectPreference(facultyId, {
        subjectTag,
        priorityLevel: Number(newPriority),
      });

      // Refresh preferences
      const preferencesData = await fetchFacultySubjectPreferences(facultyId);
      setPreferences(preferencesData.preferences || []);
      setPrepLimit(Number(preferencesData.prepLimit ?? 4));
      setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
      setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
      setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));
      setSubjectSearchQuery('');
      await refreshPreferenceRecords();

      setSuccessMessage('Priority updated successfully');
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error updating priority:', err);
      setError(err instanceof Error ? err.message : 'Failed to update priority');
    }
  };

  const executeAutoGenerate = async () => {
    try {
      setError(null);
      setIsAutoGenerating(true);

      // Call the inverted generator: build specialization keywords from selected preferences
      const result = await autoGenerateSpecializationFromPreferences(facultyId);
      setAutoGeneratedPreview(Array.isArray(result.generated) ? result.generated : []);

      // Refresh preferences
      const preferencesData = await fetchFacultySubjectPreferences(facultyId);
      setPreferences(preferencesData.preferences || []);
      setPrepLimit(Number(preferencesData.prepLimit ?? 4));
      setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
      setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
      setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));
      setSubjectSearchQuery('');
      await refreshPreferenceRecords();

      const savedText = result.saved ? ` Saved: ${result.saved}` : '';
      const saveErr = result.saveError ? ` Save error: ${result.saveError}` : '';
      setSuccessMessage(`Auto-generated and saved ${result.count} specialization keyword(s).${savedText}${saveErr}`);
      // Notify parent to refresh faculty list/details when saved successfully
      if (result.saved && typeof onSaved === 'function') {
        try {
          onSaved();
        } catch (e) {
          console.warn('onSaved callback failed', e);
        }
      }
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error auto-generating preferences:', err);
      setError(err instanceof Error ? err.message : 'Failed to auto-generate preferences');
    } finally {
      setIsAutoGenerating(false);
    }
  };

  // Handle auto-generation
  const handleAutoGenerate = async () => {
    setConfirmDialog({
      type: 'auto-generate',
      title: 'Auto-generate specialization?',
      message: "This will auto-generate specialization keywords from the faculty's selected subject preferences and save them. Continue?",
      confirmLabel: 'Generate',
    });
  };

  // Get subject display name
  const getSubjectDisplay = (subject) => {
    if (!subject) return 'Unknown Subject';
    const parts = [];
    if (subject.subject_code) parts.push(subject.subject_code);
    if (subject.subject_descriptive_title) parts.push(`${subject.subject_descriptive_title}`);
    return parts.join(' - ') || 'Unknown Subject';
  };

  const getTagUsageLabel = (subjectCode) => {
    const count = Number(tagUsageCounts[String(subjectCode || '').toUpperCase()] || 0);
    return String(count);
  };

  const getTagUsageTone = (subjectCode) => {
    const count = Number(tagUsageCounts[String(subjectCode || '').toUpperCase()] || 0);
    if (count <= 0) return 'tone-green';
    if (count <= 3) return 'tone-yellow';
    return 'tone-red';
  };

  const getSubjectByCode = (subjectCode) =>
    availableSubjects.find(
      (subject) => String(subject.subject_code || '').toUpperCase() === String(subjectCode || '').toUpperCase()
    );

  const normalizeSearchText = (value) =>
    String(value || '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, ' ')
      .trim();

  const compactSearchText = (value) =>
    String(value || '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '');

  const matchesSearchQuery = (subject, query) => {
    const normalizedQuery = normalizeSearchText(query);
    if (!normalizedQuery) return true;
    const subjectCode = normalizeSearchText(subject.subject_code);
    const subjectTitle = normalizeSearchText(subject.subject_descriptive_title);
    const subjectDisplay = normalizeSearchText(getSubjectDisplay(subject));
    const compactQuery = compactSearchText(query);
    const compactCode = compactSearchText(subject.subject_code);
    const compactTitle = compactSearchText(subject.subject_descriptive_title);
    const compactDisplay = compactSearchText(getSubjectDisplay(subject));
    const queryParts = normalizedQuery.split(/\s+/).filter(Boolean);

    if (
      compactQuery &&
      (
        compactCode.includes(compactQuery) ||
        compactTitle.includes(compactQuery) ||
        compactDisplay.includes(compactQuery)
      )
    ) {
      return true;
    }

    return queryParts.every((part) => {
      return (
        subjectCode.includes(part) ||
        subjectTitle.includes(part) ||
        subjectDisplay.includes(part)
      );
    });
  };

  // Get subjects not yet tagged and that fit remaining capacity
  const untaggedSubjects = availableSubjects.filter((subject) => {
    const code = subject.subject_code?.toUpperCase();
    if (!code) return false;
    if (preferences.some((pref) => pref.subject_tag === code)) return false;
    const units = Number(subject.subject_units || 0);
    if (remainingUnits <= 0) return false;
    return units <= remainingUnits;
  });

  // Compute a relevance score for each candidate and sort by relevance so
  // the most relevant subjects appear on top instead of preserving input order.
  const scoreSubjectMatch = (subject, query) => {
    const qNorm = normalizeSearchText(query);
    const qCompact = compactSearchText(query);
    if (!qNorm) return 100; // no query — keep original ordering but high score so appears

    const code = String(subject.subject_code || '').toLowerCase();
    const title = normalizeSearchText(subject.subject_descriptive_title || '');
    const display = normalizeSearchText(getSubjectDisplay(subject));
    const compactCode = compactSearchText(subject.subject_code || '');
    const compactTitle = compactSearchText(subject.subject_descriptive_title || '');

    // Start with a base score if the legacy matcher considers it a match
    let score = matchesSearchQuery(subject, query) ? 100 : 0;

    // Exact code match (highest)
    if (compactCode === qCompact && qCompact) score += 1000;
    // Code starts with query
    if (compactCode.startsWith(qCompact) && qCompact) score += 500;
    // Code contains query
    if (compactCode.includes(qCompact) && qCompact) score += 250;

    // Title exact phrase
    if (display.includes(qNorm) && qNorm) score += 200;
    // Title token matches: more tokens matched -> higher score
    const qParts = qNorm.split(/\s+/).filter(Boolean);
    let titleMatchCount = 0;
    for (const p of qParts) {
      if (title.includes(p) || display.includes(p)) titleMatchCount += 1;
    }
    score += titleMatchCount * 50;

    // Fallback small score if compact display contains compact query
    if (compactTitle.includes(qCompact) || compactCode.includes(qCompact)) score += 10;

    return score;
  };

  const searchableSubjects = (() => {
    // Map candidates to scored objects
    const scored = untaggedSubjects.map((subject) => ({
      subject,
      score: scoreSubjectMatch(subject, subjectSearchQuery),
    }));

    // Filter out non-matches when query present
    const filtered = subjectSearchQuery
      ? scored.filter((s) => s.score > 0)
      : scored;

    // Sort by score desc, then by subject_code asc for stability
    filtered.sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      const aCode = String(a.subject.subject_code || '');
      const bCode = String(b.subject.subject_code || '');
      return aCode.localeCompare(bCode);
    });

    // no debug logging

    return filtered.map((f) => f.subject);
  })();

  const openSubjectMenu = () => {
    if (untaggedSubjects.length === 0 || isAdding || remainingUnits <= 0) return;
    setIsSubjectMenuOpen((open) => !open);
  };

  const executeDeletePreferenceRecord = async (record) => {
    try {
      setRecordError(null);
      setRecordActionId(record.id);
      await deleteFacultyPreferenceRecord(facultyId, record.id);
      await refreshPreferenceRecords();
      setSuccessMessage('Preference record deleted successfully');
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error deleting preference record:', err);
      setRecordError(err instanceof Error ? err.message : 'Failed to delete preference record');
    } finally {
      setRecordActionId(null);
    }
  };

  const handleDeletePreferenceRecord = async (record) => {
    setConfirmDialog({
      type: 'delete-record',
      title: 'Delete archive record?',
      message: 'Are you sure you want to delete this record?',
      confirmLabel: 'Delete record',
      recordId: record.id,
    });
  };

  const handleConfirmDialogConfirm = async () => {
    const dialog = confirmDialog;
    if (!dialog) return;

    setConfirmDialog(null);

    if (dialog.type === 'delete-preference') {
      await executeDeletePreference(dialog.subjectTag);
      return;
    }

    if (dialog.type === 'delete-record') {
      const record = preferenceRecords.find((item) => item.id === dialog.recordId);
      if (record) await executeDeletePreferenceRecord(record);
      return;
    }

    if (dialog.type === 'auto-generate') {
      await executeAutoGenerate();
    }
  };

  const handleReAddPreferenceRecord = async (record) => {
    try {
      setRecordError(null);
      setRecordActionId(record.id);

      await addFacultySubjectPreference(facultyId, {
        subjectTag: record.subject_tag,
        priorityLevel: Number(record.priority_level || 2),
      });

      const preferencesData = await fetchFacultySubjectPreferences(facultyId);
      setPreferences(preferencesData.preferences || []);
      setPrepLimit(Number(preferencesData.prepLimit ?? 4));
      setFacultyMaxUnits(Number(preferencesData.facultyMaxUnits ?? 0));
      setUsedTaggedUnits(Number(preferencesData.usedTaggedUnits ?? 0));
      setRemainingUnits(Number(preferencesData.remainingUnits ?? 0));
      await refreshPreferenceRecords();

      setSuccessMessage('Preference re-added successfully');
      setTimeout(() => setSuccessMessage(null), 3000);
    } catch (err) {
      console.error('Error re-adding preference record:', err);
      setRecordError(err instanceof Error ? err.message : 'Failed to re-add preference record');
    } finally {
      setRecordActionId(null);
    }
  };

  // subject status availableCount/taggedCount/untaggedCount

  if (loading) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-header">
            <h2>Subject Preferences</h2>
            <button className="modal-close" onClick={onClose}>×</button>
          </div>
          <div className="modal-body">
            <p>Loading...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Subject Preferences</h2>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>

        <div className="modal-body">
          {/* Error Message */}
          {error && <div className="alert alert-error">{error}</div>}

          {/* Success Message */}
          {successMessage && <div className="alert alert-success">{successMessage}</div>}
          {confirmDialog && (
            <div className="confirm-backdrop" onClick={() => setConfirmDialog(null)}>
              <div className="confirm-dialog" onClick={(e) => e.stopPropagation()}>
                <h3>{confirmDialog.title}</h3>
                <p>{confirmDialog.message}</p>
                <div className="confirm-actions">
                  <button type="button" className="btn btn-default" onClick={() => setConfirmDialog(null)}>
                    Cancel
                  </button>
                  <button type="button" className="btn btn-primary" onClick={handleConfirmDialogConfirm}>
                    {confirmDialog.confirmLabel}
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Faculty Name */}
          <div className="faculty-info">
            <strong>Faculty:</strong> {facultyName}
          </div>

          {/* Add Subject Tag Section */}
          <div className="add-subject-section">
            <h3>Add Subject Tag</h3>
            <div className="add-subject-form">
              <div className="subject-select-wrapper" ref={subjectMenuRef}>
                <button
                  type="button"
                  className="subject-select-button"
                  onClick={openSubjectMenu}
                  disabled={untaggedSubjects.length === 0 || isAdding || remainingUnits <= 0}
                >
                  <span className="subject-select-button-label">
                    {selectedSubjectCode
                      ? getSubjectDisplay(
                          availableSubjects.find((subject) => subject.subject_code === selectedSubjectCode)
                        )
                      : remainingUnits <= 0
                      ? `No remaining units (${usedTaggedUnits}/${facultyMaxUnits})`
                      : untaggedSubjects.length === 0
                      ? 'No eligible subjects available'
                      : 'Select a subject...'}
                  </span>
                  <span className="subject-select-button-caret">▾</span>
                </button>

                {isSubjectMenuOpen && untaggedSubjects.length > 0 && remainingUnits > 0 && (
                  <div className="subject-select-menu">
                    <div className="subject-search-wrapper">
                      <input
                        type="text"
                        className="subject-search-input"
                        placeholder="Search subject code or title..."
                        value={subjectSearchQuery}
                        onChange={(e) => setSubjectSearchQuery(e.target.value)}
                        ref={subjectSearchInputRef}
                        onClick={(e) => e.stopPropagation()}
                        onKeyDown={(e) => e.stopPropagation()}
                      />
                    </div>

                    {searchableSubjects.length === 0 ? (
                      <div className="subject-search-empty">No matching subjects</div>
                    ) : (
                      searchableSubjects.map((subject, idx) => {
                        const code = subject.subject_code;
                        const countLabel = getTagUsageLabel(code);
                        const uniqueKey = `${String(code || '')}__${String(subject.subject_descriptive_title || '')}__${idx}`;
                        return (
                          <button
                            key={uniqueKey}
                            type="button"
                            className="subject-select-option"
                            onClick={() => {
                              setSelectedSubjectCode(code);
                              setSubjectSearchQuery('');
                              setIsSubjectMenuOpen(false);
                            }}
                          >
                            <span className="subject-select-option-text">
                              {getSubjectDisplay(subject)}
                            </span>
                            <span className={`subject-count-pill ${getTagUsageTone(code)}`}>
                              {countLabel}
                            </span>
                          </button>
                        );
                      })
                    )}
                  </div>
                )}
              </div>

              <select
                value={selectedPriority}
                onChange={(e) => setSelectedPriority(e.target.value)}
                className="priority-select"
                disabled={isAdding}
              >
                <option value="">Select priority</option>
                {Object.entries(PRIORITY_LABELS).map(([level, label]) => (
                  <option key={level} value={level}>
                    {level} - {label}
                  </option>
                ))}
              </select>

              <button
                onClick={handleAddPreference}
                className="btn btn-primary"
                disabled={!selectedSubjectCode || !selectedPriority || isAdding || remainingUnits <= 0}
              >
                {isAdding ? 'Adding...' : 'Add'}
              </button>
            </div>
          </div>

          {/* Auto-Generate Button */}
          <div className="auto-generate-section">
            <h3>Auto-Generate Specialization</h3>
            <button
              onClick={handleAutoGenerate}
              className="btn btn-secondary"
              disabled={isAutoGenerating}
            >
              {isAutoGenerating ? 'Generating...' : 'Auto-Generate'}
            </button>
            <p className="help-text">
              Runs a confirmation popup before generating specialization keywords from the faculty's selected subject preferences and saving them to the faculty record.
            </p>
            {autoGeneratedPreview.length > 0 && (
              <div className="auto-generated-preview">
                <div className="auto-generated-preview-title">Generated preview</div>
                <div className="auto-generated-preview-list">
                  {autoGeneratedPreview.map((item, idx) => {
                    if (typeof item === 'string') {
                      return (
                        <div key={`spec-${idx}`} className="auto-generated-preview-item">
                          <span className="auto-generated-preview-code">{item}</span>
                        </div>
                      );
                    }
                    const subject = getSubjectByCode(item.subject_tag);
                    return (
                      <div key={`${item.subject_tag}-${item.priority_level}`} className="auto-generated-preview-item">
                        <span className="auto-generated-preview-code">{item.subject_tag}</span>
                        <span className="auto-generated-preview-name">
                          {subject?.subject_descriptive_title || 'Matched subject'}
                        </span>
                        <span className="auto-generated-preview-priority">
                          P{item.priority_level}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          {/* Teaching Record Section */}
          <div className="current-tags-section">
            <div className="record-summary-header">
              <h3>Current Teaching Record</h3>
              <div className="record-summary-count">{preferences.length} live tags</div>
            </div>
            <div className="prep-slot-breakdown record-summary-metrics">
              <span className="prep-slot-item prep-slot-p1" title="Total units already used by selected tags">
                Used: {usedTaggedUnits}
              </span>
              <span className="prep-slot-divider">·</span>
              <span className="prep-slot-item prep-slot-p2" title="Faculty maximum units">
                Max: {facultyMaxUnits}
              </span>
              <span className="prep-slot-divider">·</span>
              <span className={`prep-slot-item prep-slot-free${remainingUnits === 0 ? ' prep-slot-free-empty' : ''}`}
                title="Units still available for adding subject tags">
                Remaining: {remainingUnits}
              </span>
            </div>
            <p className="help-text">
              Update the live teaching record by adding or removing selected tags below.
            </p>

            {preferences.length > 0 && (() => {
              const p1Count = preferences.filter(p => p.priority_level === 1).length;
              const p2Count = preferences.filter(p => p.priority_level === 2).length;
              const p3Count = preferences.filter(p => p.priority_level === 3).length;
              const remaining = Math.max(0, prepLimit - preferences.length);
              return (
                <div className="prep-slot-breakdown">
                  <span className="prep-slot-item prep-slot-p1" title="Hard pre-assigned before GA runs">
                    P1 (High): {p1Count}
                  </span>
                  <span className="prep-slot-divider">·</span>
                  <span className="prep-slot-item prep-slot-p2" title="Prep slot reserved for GA">
                    P2 (Capable): {p2Count}
                  </span>
                  <span className="prep-slot-divider">·</span>
                  <span className="prep-slot-item prep-slot-p3" title="Prep slot reserved for GA">
                    P3 (Fallback): {p3Count}
                  </span>
                  <span className="prep-slot-divider">·</span>
                  <span className={`prep-slot-item prep-slot-free${remaining === 0 ? ' prep-slot-free-empty' : ''}`}
                    title="Remaining slots the GA can fill from department matching">
                    Free for GA: {remaining}
                  </span>
                </div>
              );
            })()}

            {preferences.length === 0 ? (
              <p className="no-tags-message">No subject preferences added yet</p>
            ) : (
              <div className="tags-list">
                {preferences.map((pref) => (
                  <div key={pref.subject_tag} className="tag-item">
                    <div className="tag-subject-info">
                      <span className="tag-code">{pref.subject_tag}</span>
                      <span
                        className="tag-title"
                        title={getSubjectByCode(pref.subject_tag)?.subject_descriptive_title || pref.subject_tag}
                      >
                        {getSubjectByCode(pref.subject_tag)?.subject_descriptive_title || pref.subject_tag}
                      </span>
                    </div>

                    <div className="tag-priority">
                      <select
                        value={pref.priority_level}
                        onChange={(e) =>
                          handleUpdatePriority(pref.subject_tag, e.target.value)
                        }
                        className="priority-badge"
                        style={{
                          backgroundColor: PRIORITY_COLORS[pref.priority_level],
                          color: 'white',
                        }}
                      >
                        {Object.entries(PRIORITY_LABELS).map(([level, label]) => (
                          <option key={level} value={level}>
                            {level} - {label}
                          </option>
                        ))}
                      </select>
                    </div>

                    <button
                      onClick={() => handleDeletePreference(pref.subject_tag)}
                      className="btn-delete"
                      title="Remove preference"
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="current-tags-section" style={{ marginTop: '1.25rem' }}>
            <div className="record-summary-header">
              <div>
                <div className="record-summary-eyebrow">Archive</div>
                <h3>Faculty Preference Records</h3>
              </div>
              <div className="record-summary-count">{preferenceRecords.length}/{preferenceRecordsTotal || preferenceRecords.length} loaded</div>
            </div>
            <p className="help-text">
              Saved history of selected tags. Use Load more to fetch older records. Delete removes only the archive row. Re-add sends the subject back to the live list.
            </p>

            {recordError && <div className="alert alert-error">{recordError}</div>}

            {recordLoading ? (
              <p className="no-tags-message">Loading preference records...</p>
            ) : preferenceRecords.length === 0 ? (
              <p className="no-tags-message">No preference records available yet</p>
            ) : (
              <div className="tags-list">
                {preferenceRecords.map((record) => (
                  <div key={record.id} className="tag-item">
                    <div className="tag-subject-info">
                      <span className="tag-code">{record.subject_tag}</span>
                      <span
                        className="tag-title"
                        title={record.subject_descriptive_title || record.subject_tag}
                      >
                        {record.subject_descriptive_title || record.subject_tag}
                      </span>
                    </div>

                    <div className="tag-priority">
                      <span
                        className="priority-badge"
                        style={{ backgroundColor: PRIORITY_COLORS[record.priority_level] || PRIORITY_COLORS[2], color: 'white' }}
                      >
                        P{record.priority_level}
                      </span>
                    </div>

                    <div className="archive-record-actions">
                      <button
                        onClick={() => handleReAddPreferenceRecord(record)}
                        className="btn btn-primary archive-action-add"
                        title="Add back to live list"
                        disabled={recordActionId === record.id}
                        type="button"
                      >
                        {recordActionId === record.id ? 'Working...' : 'Add'}
                      </button>
                      <button
                        onClick={() => handleDeletePreferenceRecord(record)}
                        className="btn-delete archive-action-delete"
                        title="Remove record"
                        disabled={recordActionId === record.id}
                        type="button"
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {preferenceRecordsHasMore && (
              <div className="mt-3 flex justify-center">
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={handleLoadMorePreferenceRecords}
                  disabled={recordLoadingMore}
                >
                  {recordLoadingMore ? 'Loading more...' : 'Load more'}
                </button>
              </div>
            )}
          </div>

          {/* Priority Levels Legend */}
          <div className="priority-legend">
            <p><strong>Priority Levels:</strong></p>
            <div className="legend-items">
              <div className="legend-item">
                <span className="legend-color" style={{ backgroundColor: PRIORITY_COLORS[1] }}></span>
                <span>1 = High (Primary assignment)</span>
              </div>
              <div className="legend-item">
                <span className="legend-color" style={{ backgroundColor: PRIORITY_COLORS[2] }}></span>
                <span>2 = Capable (Secondary/backup)</span>
              </div>
              <div className="legend-item">
                <span className="legend-color" style={{ backgroundColor: PRIORITY_COLORS[3] }}></span>
                <span>3 = Fallback (Emergency coverage)</span>
              </div>
            </div>
          </div>
        </div>

        <div className="modal-footer">
          <button onClick={onClose} className="btn btn-default">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
